apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: cli-tools
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/openshift/cli
    referencePolicy:
      type: Source
